class Trace:
    def __init__(self, name, input = None, fast_forward = 0, sim_end = 1E6, trace=False):
        self.name = name
        self.input = input
        self.fast_forward = fast_forward
        self.sim_end = sim_end
        self.trace = trace

traces = [
    Trace(
        name="telemetry_youtube",
        input="youtube.gltrace",
        fast_forward=0,
        sim_end=177
    ),
    Trace(
        name="telemetry_wikipedia",
        input="wikipedia.gltrace",
        fast_forward=0,
        sim_end=378
    ),
    Trace(
        name="telemetry_twitter",
        input="twitter.gltrace",
        fast_forward=0,
        sim_end=286
    ),
    Trace(
        name="telemetry_techcrunch",
        input="techcrunch.gltrace",
        fast_forward=0,
        sim_end=488
    ),
    Trace(
        name="telemetry_sports_yahoo",
        input="sports_yahoo.gltrace",
        fast_forward=0,
        sim_end=398
    ),
    Trace(
        name="telemetry_reddit",
        input="reddit.gltrace",
        fast_forward=0,
        sim_end=165
    ),
    Trace(
        name="telemetry_news_yahoo",
        input="news_yahoo.gltrace",
        fast_forward=0,
        sim_end=229
    ),
    Trace(
        name="telemetry_google",
        input="google.gltrace",
        fast_forward=0,
        sim_end=165
    ),
    Trace(
        name="telemetry_facebook",
        input="facebook.gltrace",
        fast_forward=0,
        sim_end=237
    ),
    Trace(
        name="telemetry_ebay",
        input="ebay.gltrace",
        fast_forward=0,
        sim_end=276
    ),
    Trace(
        name="telemetry_cnn",
        input="cnn.gltrace",
        fast_forward=0,
        sim_end=455
    ),
    Trace(
        name="telemetry_booking",
        input="booking.gltrace",
        fast_forward=0,
        sim_end=417
    ),
    Trace(
        name="telemetry_answers_yahoo",
        input="answers_yahoo.gltrace",
        fast_forward=0,
        sim_end=195
    ),
    Trace(
        name="telemetry_amazon",
        input="amazon.gltrace",
        fast_forward=0,
        sim_end=309
    ),
    Trace(
        name="ue4_tappy_chicken",
        input="ue4-tappy-chicken.gltrace",
        fast_forward=20,
        sim_end=5000
    ),
    Trace(
        name="pts_tesseract_1.1.0_1920x1200",
        input="pts-tesseract-1.1.0-1920x1200.gltrace",
        fast_forward=410,
        sim_end=906
    ),
    Trace(
        name="pts_unigine_heaven_1.6.2_1920x1200",
        input="pts-unigine-heaven-1.6.2-1920x1200.gltrace",
        fast_forward=110,
        sim_end=161
    ),
    Trace(
        name="pts_unigine_valley_1.1.4_1920x1200",
        input="pts-unigine-valley-1.1.4-1920x1200.gltrace",
        fast_forward=110,
        sim_end=163
    ),
    Trace(
        name="pts_openarena_1.5.3_1920x1200",
        input="pts-openarena-1.5.3-1920x1200.gltrace",
        fast_forward=45,
        sim_end=1148
    ),
    Trace(
        name="pts_xonotic_1.4.0_1920x1200_LD",
        input="pts-xonotic-1.4.0-1920x1200-Low.gltrace",
        fast_forward=65,
        sim_end=3475
    ),
    Trace(
        name="pts_xonotic_1.4.0_1920x1200_UD",
        input="pts-xonotic-1.4.0-1920x1200-Ultimate.gltrace",
        fast_forward=65,
        sim_end=1116
    ),
    Trace(
        name="gfxbench_manhattan_1920x1200",
        input="gfxbench-manhattan-1920x1200.gltrace",
        fast_forward=0,
        sim_end=1079
    ),
    Trace(
        name="gfxbench_trex_1920x1200",
        input="gfxbench-trex-1920x1200.gltrace",
        fast_forward=0,
        sim_end=1507
    ),
]

